locale = "en"
label = "English"
direction = "ltr"
contentDir = "content/en"
weight = 1

title = "Léopold Trémant"
# copyright = "Léopold Trémant"

[params]
  # dateFormat = "2 January 2006"
  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
  name = "Léopold Trémant"
  image = "img/author.jpg"
  imageAlt = "Drawing of myself by the wonderful Marie Morin (Instagram @marmo.graphics)"
  headline = "Assistant professor, Université d'Artois"
  bio = "Assistant professor, Université d'Artois"