locale = "fr"
label = "Français"
direction = "ltr"
contentDir = "content/fr"
weight = 2

title = "Léopold Trémant"
# copyright = "Léopold Trémant"

[params]
  # dateFormat = "2 janvier 2006"
  # mainSections = ["section1", "section2"]
  # description = "Mon super site"

[params.author]
  imageAlt = "Portrait réalisé par l'incroyable Marie Morin (Instagram @marmo.graphics)"
  headline = "Maître de Conférences, Université d'Artois"
  bio = "Maître de Conférences, Université d'Artois"
